"""add stage column to match

Revision ID: 4fd5ae6e5f9b
Revises: 906a8f9943d7
Create Date: 2026-07-08 22:33:17.637309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4fd5ae6e5f9b'
down_revision: Union[str, Sequence[str], None] = '906a8f9943d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'stage')
    # ### end Alembic commands ###
